# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(594, 475)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 0, 571, 461))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dataEdit = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.dataEdit.setObjectName("dataEdit")
        self.verticalLayout.addWidget(self.dataEdit)
        self.copyButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.copyButton.setObjectName("copyButton")
        self.verticalLayout.addWidget(self.copyButton)
        self.pasteButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pasteButton.setObjectName("pasteButton")
        self.verticalLayout.addWidget(self.pasteButton)
        self.resultEdit = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.resultEdit.setObjectName("resultEdit")
        self.verticalLayout.addWidget(self.resultEdit)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.copyButton.setText(_translate("Dialog", "Kopiuj"))
        self.pasteButton.setText(_translate("Dialog", "Wklej"))
